### ISSUE TITLE
Error during Ios build

### ISSUE THREAD

**Issue by codenomaddev** [nextbillion-ai/nb-navigation-flutter#44]
ERROR: The named parameter 'size' isn't defined.

Xcode 15.3

This LIB has been included in [ANALYSIS ISSUE] related to this subject.

**Comment by qiuyulv** [comment]
@codenomaddev a new version [v0.4.3](https://pub-web.flutter-io.cn/packages/nb_navigation_flutter/changelog) has been uploaded, to fix the build error by configuring the minimum flutter version to 3.22.0

**Comment by zhengshenqiu** [comment]
The issue was fixed from version [v0.4.3](https://pub-web.flutter-io.cn/packages/nb_navigation_flutter/changelog) ,So this issue can be closed

**Comment by zhengshenqiu** [comment]
Issue was fixed
